- url: "https://www.alza.cz/nothing-eara-white-d12302496.htm#description"
  nazev: "Sluchátka nothing"
- url: "https://www.alza.cz/xiaomi-h50-pro-d13331273.htm"
  nazev: "Vysavač Xiomi"
- url: "https://www.alza.cz/wanbo-mozart-1-pro-new-d12949979.htm#description"
  nazev: "Promítačka"
- url: "https://www.alza.cz/gaming/nintendo-switch-2-pokemon-pokopia-d13427741.htm"
  nazev: "Nintendo"
- url: "https://www.alza.cz/insta360-x6-essential-bundle-mic-pro-edition-black-d13496633.htm"
  nazev: "Insta Kamera"
